In [3]:
import numpy as np
import pandas as pd

In [5]:
github_url ="https://raw.githubusercontent.com/campusx-official/ml-model-deployment-aws-ec2/main/students_placement.csv"
df = pd.read_csv(github_url)

In [6]:
df.head()

cgpa   iq  profile_score  placed
0  5.97  106             61       0
1  6.83  113             77       0
2  6.60  110             61       0
3  5.54  113             68       0
4  6.84  102             67       0

In [19]:
df.sample(5)

cgpa   iq  profile_score  placed
29   7.21   96             94       1
298  7.00   90             28       1
251  7.62   97             43       1
285  8.70   96             56       1
215  7.00  104             48       0

In [7]:
df.shape

(300, 4)

In [8]:
X = df.drop(columns=['placed'])
y = df['placed']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
scaler = StandardScaler()
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)
accuracy_score(y_test,
               LogisticRegression()
               .fit(X_train_trf,y_train)
               .predict(X_test_trf))

0.8833333333333333

In [12]:
from sklearn.ensemble import RandomForestClassifier
accuracy_score(y_test,RandomForestClassifier().fit(X_train,y_train).predict(X_test))

0.8833333333333333

In [13]:
from sklearn.svm import SVC
accuracy_score(y_test,SVC(kernel='rbf').fit(X_train,y_train).predict(X_test))

0.9333333333333333

In [14]:
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

SVC()

In [15]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [17]:
import pickle 
pickle.dump(svc,open('model1.pkl','wb'))

In [20]:
rf.predict(np.array([7.21,96,94]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [25]:
svc.predict(np.array([7.21,96,94]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [21]:
rf.predict(np.array([4.5,56,10]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [26]:
svc.predict(np.array([4.5,56,10]).reshape(1,3)) #svc giving wrong prediction

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [22]:
rf.predict(np.array([0,0,0]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [23]:
model = pickle.load(open('model1.pkl','rb'))

In [24]:
model.predict(np.array([0,0,0]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [27]:
pickle.dump(rf,open('model_rf.pkl','wb'))

In [29]:
model_rf_load = pickle.load(open('model_rf.pkl','rb'))

In [31]:
model_rf_load.predict(np.array([0,0,0]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [32]:
model_rf_load.predict(np.array([5.97,106,67]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [33]:
model_rf_load.predict(np.array([7.21,96,94]).reshape(1,3))

c:\Users\Prajwal\Desktop\Ml_model_deployment\test_deployment\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)